steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/norse-habitat-349912/cloud-run-webapp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/norse-habitat-349912/cloud-run-webapp']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloud-run-webapp', '--image', 'gcr.io/norse-habitat-349912/cloud-run-webapp', '--region', 'us-central1']
images:
- gcr.io/norse-habitat-349912/cloud-run-webapp